sqldf("select * form stu")
sqldf("select count(*) from stu")
sqldf("select * from stu where marks>80")
sqldf("select * from stu where marks<80")
sqldf("select * from stu where name = veer")
sqldf("select * from stu where marks==45")
sqldf("select name from stu where marks==45")
sqldf("select distinct name from stu")
min(students&marks)
max(students&marks)
sum(students&marks)
nrow(students[students&marks=33,])
nrow(students[students&marks>33,])
sqldf("select * from stu limits 3")
sqldf("select * from stu order by name desc limit 4")
sqldf("select name,marks from stu order by name,marks desc limit 3")
sqldf("select * from stu order by name desc")
sqldf("select * from stu where name like '%s'")
sqldf("select * from stu where name like 'v%'")
sqldf("select * from stu where name like 'k%'")
sqldf("select name as N, marks as M from stu")
sqldf("select sum(marks) from stu")
sqldf("select avg(sum) from stu")